<!DOCTYPE html>
<html>
<head>
    <title>Daily Visitor Report</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #4f46e5; color: white; padding: 20px; text-align: center; }
        .stats { display: flex; justify-content: space-around; margin: 20px 0; }
        .stat-box { text-align: center; padding: 15px; background: #f3f4f6; border-radius: 8px; }
        .stat-number { font-size: 24px; font-weight: bold; color: #4f46e5; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f3f4f6; font-weight: bold; }
        .status-active { color: #059669; }
        .status-completed { color: #6b7280; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Daily Visitor Report</h1>
            <p>{{ \Carbon\Carbon::parse($data['date'])->format('F d, Y') }}</p>
        </div>

        <div class="stats">
            <div class="stat-box">
                <div class="stat-number">{{ $data['totalVisitors'] }}</div>
                <div>Total Visitors</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">{{ $data['activeVisitors'] }}</div>
                <div>Active</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">{{ $data['completedVisits'] }}</div>
                <div>Completed</div>
            </div>
        </div>

        <h2>Visitor Details</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Purpose</th>
                    <th>Host</th>
                    <th>Time In</th>
                    <th>Time Out</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['visitors'] as $visitor)
                <tr>
                    <td>{{ $visitor->full_name }}</td>
                    <td>{{ $visitor->purpose }}</td>
                    <td>{{ $visitor->host_name }}</td>
                    <td>{{ $visitor->time_in->format('h:i A') }}</td>
                    <td>{{ $visitor->time_out ? $visitor->time_out->format('h:i A') : '-' }}</td>
                    <td class="{{ $visitor->isActive() ? 'status-active' : 'status-completed' }}">
                        {{ $visitor->isActive() ? 'Active' : 'Completed' }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <p style="margin-top: 30px; color: #6b7280; font-size: 12px; text-align: center;">
            Generated by Visitor Log Monitoring System<br>
            Supporting SDG 16: Peace, Justice, and Strong Institutions
        </p>
    </div>
</body>
</html>